(function(){
'use strict';
const STORE='nadiia-scanwords-v7';
const puzzles=window.SCANWORD_PUZZLES||[];
const EXTRA=[...'АЕИОУЫЭЮЯБВГДЖЗЙКЛМНПРСТФХЦЧШЩ'];
const $=selector=>document.querySelector(selector);
const els={game:$('#game-screen'),grid:$('#scanword-grid'),board:$('.board-area'),tiles:$('#letter-tiles'),clue:$('#current-clue'),label:$('#puzzle-label'),progress:$('#progress-bar'),feedback:$('#feedback'),dialog:$('#complete-dialog'),drawer:$('#drawer'),hints:$('#hints-sheet'),input:$('#native-input'),list:$('#puzzle-list')};
let saved=readSaved(),state=null,toastTimer=0;
function readSaved(){try{return JSON.parse(localStorage.getItem(STORE)||'{}')}catch{return {}}}
function persist(){try{localStorage.setItem(STORE,JSON.stringify(saved))}catch{}}
function key(row,col){return `${row}:${col}`}
function delta(word){return word.direction==='down'?[1,0]:word.direction==='left'?[0,-1]:[0,1]}
function wordCells(word){const [dr,dc]=delta(word);return [...word.answer].map((letter,index)=>({key:key(word.row+dr*index,word.col+dc*index),letter,index}))}
function solution(puzzle){const map={};puzzle.words.forEach(word=>wordCells(word).forEach(cell=>{map[cell.key]||={letter:cell.letter,wordIds:[]};map[cell.key].wordIds.push(word.id)}));return map}
function arrowFor(word){return word.arrow||(word.direction==='down'?'↓':word.direction==='left'?'←':'→')}
function activeWord(){return state.puzzle.words.find(word=>word.id===state.activeWordId)}
function wordDone(word){return wordCells(word).every(cell=>state.cells[cell.key]===cell.letter)}
function puzzleDone(){return state&&Object.entries(state.solution).every(([cellKey,value])=>state.cells[cellKey]===value.letter)}
function saveGame(){if(!state)return;saved[state.puzzle.id]={cells:state.cells,completed:puzzleDone(),updatedAt:Date.now()};persist()}
function resizeBoard(){
 if(!state)return;
 const {cols,rows}=state.puzzle;
 const availableWidth=els.board.clientWidth;
 const chromeHeight=$('.game-head').offsetHeight+$('.clue-bar').offsetHeight+els.tiles.offsetHeight+$('.game-foot').offsetHeight;
 const availableHeight=Math.max(rows*24,window.innerHeight-chromeHeight-envSafeArea());
 let cellSize=Math.floor(Math.min(availableWidth/cols,availableHeight/rows));
 if(state.zoomed)cellSize=Math.floor(cellSize*1.14);
 cellSize=Math.max(24,cellSize);
 document.documentElement.style.setProperty('--cell',`${cellSize}px`);
 document.documentElement.style.setProperty('--board-cols',cols);
 document.documentElement.style.setProperty('--board-rows',rows);
 els.board.style.height=`${cellSize*rows}px`;
}
function envSafeArea(){return 0}
function openPuzzle(puzzle){const prior=saved[puzzle.id]||{};state={puzzle,solution:solution(puzzle),cells:{...(prior.cells||{})},activeWordId:puzzle.words[0].id,focus:0,solved:new Set(puzzle.words.filter(word=>wordCells(word).every(cell=>prior.cells?.[cell.key]===cell.letter)).map(word=>word.id)),tileOrder:{},extrasMuted:false,zoomed:false};els.dialog.hidden=true;els.board.classList.remove('is-zoomed');selectWord(puzzle.words[0].id,true);renderPuzzleList();requestAnimationFrame(resizeBoard)}
function renderBoard(){const clues=new Map(state.puzzle.words.map(word=>[key(word.clueCell.row,word.clueCell.col),word])),active=activeWord(),activeCells=wordCells(active),activeKeys=new Set(activeCells.map(cell=>cell.key)),focusKey=activeCells[state.focus]?.key,fragment=document.createDocumentFragment();for(let row=0;row<state.puzzle.rows;row+=1)for(let col=0;col<state.puzzle.cols;col+=1){const cellKey=key(row,col),word=clues.get(cellKey),sol=state.solution[cellKey];if(!word&&!sol)throw new Error(`Пустая клетка ${cellKey}`);const element=document.createElement('button');element.className='grid-cell';if(word){element.classList.add('clue');element.dataset.wordId=word.id;element.dataset.direction=word.direction;if(word.id===state.activeWordId)element.classList.add('is-active');element.innerHTML=`<span class="clue-text">${word.clue}</span><b class="clue-arrow">${arrowFor(word)}</b>`;element.setAttribute('aria-label',`${word.clue}, ${arrowFor(word)}, ${word.answer.length} букв`);element.onclick=()=>selectWord(word.id)}else{element.classList.add('answer');element.textContent=state.cells[cellKey]||'';if(activeKeys.has(cellKey))element.classList.add('is-active');if(focusKey===cellKey)element.classList.add('is-focus');if(sol.wordIds.every(id=>state.solved.has(id)))element.classList.add('is-solved');element.onclick=()=>selectCell(cellKey)}fragment.append(element)}els.grid.replaceChildren(fragment)}
function selectWord(id,initial=false){state.activeWordId=id;const cells=wordCells(activeWord()),firstEmpty=cells.findIndex(cell=>!state.cells[cell.key]);state.focus=firstEmpty<0?0:firstEmpty;state.extrasMuted=false;render();if(!initial)els.grid.querySelector('.is-focus')?.focus({preventScroll:true})}
function selectCell(cellKey){const ids=state.solution[cellKey].wordIds;state.activeWordId=ids.length>1&&ids.includes(state.activeWordId)?ids[(ids.indexOf(state.activeWordId)+1)%ids.length]:ids[0];state.focus=wordCells(activeWord()).findIndex(cell=>cell.key===cellKey);state.extrasMuted=false;render()}
function random(seed){let hash=2166136261;for(const char of seed)hash=Math.imul(hash^char.charCodeAt(0),16777619);return()=>((hash=Math.imul(hash^(hash>>>15),2246822507))>>>0)/4294967296}
function tileSet(word){if(state.tileOrder[word.id])return state.tileOrder[word.id];const rand=random(state.puzzle.id+word.id),all=[...word.answer].map((letter,index)=>({letter,extra:false,id:'a'+index}));while(all.length<20)all.push({letter:EXTRA[Math.floor(rand()*EXTRA.length)],extra:true,id:'e'+all.length});for(let index=all.length-1;index>0;index-=1){const swap=Math.floor(rand()*(index+1));[all[index],all[swap]]=[all[swap],all[index]]}return state.tileOrder[word.id]=all}
function renderTiles(){const tiles=tileSet(activeWord());els.tiles.replaceChildren(...tiles.map(tile=>{const button=document.createElement('button');button.className=`letter-tile${tile.extra?' is-extra':''}${state.extrasMuted&&tile.extra?' is-muted':''}`;button.textContent=tile.letter;button.disabled=state.extrasMuted&&tile.extra;button.onclick=()=>enter(tile.letter);return button}))}
function nextEmpty(cells,start){for(let count=0;count<cells.length;count+=1){const index=(start+count)%cells.length;if(!state.cells[cells[index].key])return index}return Math.min(start,cells.length-1)}
function enter(letter){if(!/^[А-ЯЁ]$/u.test(letter))return;const cells=wordCells(activeWord()),index=state.focus;state.cells[cells[index].key]=letter;state.focus=nextEmpty(cells,index+1);afterEdit()}
function erase(){const cells=wordCells(activeWord());let index=state.focus;if(!state.cells[cells[index].key]&&index>0)index-=1;delete state.cells[cells[index].key];state.focus=index;state.solved.delete(state.activeWordId);saveGame();render()}
function reveal(){const cells=wordCells(activeWord()),index=cells.findIndex(cell=>state.cells[cell.key]!==cell.letter);if(index<0)return;state.cells[cells[index].key]=cells[index].letter;state.focus=nextEmpty(cells,index+1);afterEdit();toast('Открыта одна буква — без штрафа.')}
function revealWord(){wordCells(activeWord()).forEach(cell=>{state.cells[cell.key]=cell.letter});afterEdit();toast('Слово открыто — можно идти дальше.')}
function afterEdit(){const newly=[];state.puzzle.words.forEach(word=>{if(wordDone(word)&&!state.solved.has(word.id)){state.solved.add(word.id);newly.push(word)}});saveGame();render();if(newly.length){toast('Верно! Отличное слово ✦');sparkleWord()}if(puzzleDone())setTimeout(finish,220)}
function sparkleWord(){const box=els.grid.getBoundingClientRect();for(let index=0;index<12;index+=1){const spark=document.createElement('i');spark.className='spark';spark.textContent='✦';spark.style.left=`${box.left+box.width/2}px`;spark.style.top=`${box.top+box.height/2}px`;spark.style.setProperty('--x',`${(Math.random()-.5)*180}px`);spark.style.setProperty('--y',`${(Math.random()-.5)*140}px`);document.body.append(spark);setTimeout(()=>spark.remove(),800)}}
function toast(message){els.feedback.textContent=message;els.feedback.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>els.feedback.classList.remove('show'),1700)}
function launchConfetti(){const canvas=$('#confetti');canvas.style.display='block';const context=canvas.getContext('2d');canvas.width=innerWidth;canvas.height=innerHeight;const bits=Array.from({length:150},()=>({x:Math.random()*canvas.width,y:-Math.random()*canvas.height*.5,v:2+Math.random()*5,s:3+Math.random()*5,h:Math.random()*360}));let frame=0;(function draw(){context.clearRect(0,0,canvas.width,canvas.height);bits.forEach(bit=>{bit.y+=bit.v;bit.x+=Math.sin((bit.y+bit.h)/28);context.fillStyle=`hsl(${bit.h} 70% 48%)`;context.fillRect(bit.x,bit.y,bit.s,bit.s*1.7)});if(frame++<150)requestAnimationFrame(draw);else{context.clearRect(0,0,canvas.width,canvas.height);canvas.style.display='none'}})()}
function finish(){if(!els.dialog.hidden)return;saveGame();launchConfetti();els.dialog.hidden=false}
function render(){renderBoard();renderTiles();const word=activeWord(),total=Object.keys(state.solution).length,done=Object.entries(state.solution).filter(([cellKey,value])=>state.cells[cellKey]===value.letter).length;els.clue.textContent=word.clue;els.label.textContent=`№${state.puzzle.number} · ${Math.round(done/total*100)}% · v7`;els.progress.style.width=`${done/total*100}%`;resizeBoard()}
function renderPuzzleList(){els.list.replaceChildren(...puzzles.map(puzzle=>{const button=document.createElement('button');button.classList.toggle('is-active',state?.puzzle.id===puzzle.id);button.textContent=`№${puzzle.number} · ${puzzle.category}${saved[puzzle.id]?.completed?' · готово':''}`;button.onclick=()=>{openPuzzle(puzzle);closeDrawer(els.drawer)};return button}))}
function openDrawer(drawer){drawer.classList.add('open');drawer.setAttribute('aria-hidden','false')}
function closeDrawer(drawer){drawer.classList.remove('open');drawer.setAttribute('aria-hidden','true')}
function moveWord(delta){const index=state.puzzle.words.findIndex(word=>word.id===state.activeWordId);selectWord(state.puzzle.words[(index+delta+state.puzzle.words.length)%state.puzzle.words.length].id)}
$('#previous-word').onclick=()=>moveWord(-1);$('#next-word').onclick=()=>moveWord(1);$('#delete-button').onclick=erase;$('#keyboard-toggle').onclick=()=>{els.input.value='';els.input.focus()};$('#hint-letter').onclick=()=>{reveal();closeDrawer(els.hints)};$('#hint-word').onclick=()=>{revealWord();closeDrawer(els.hints)};$('#hint-extras').onclick=()=>{state.extrasMuted=true;renderTiles();toast('Лишние буквы приглушены.');closeDrawer(els.hints)};$('#menu-button').onclick=()=>openDrawer(els.drawer);$('#hints-button').onclick=()=>openDrawer(els.hints);$('#close-menu').onclick=()=>closeDrawer(els.drawer);$('#close-hints').onclick=()=>closeDrawer(els.hints);[els.drawer,els.hints].forEach(drawer=>drawer.onclick=event=>{if(event.target===drawer)closeDrawer(drawer)});$('#layout-button').onclick=()=>{state.zoomed=!state.zoomed;els.board.classList.toggle('is-zoomed',state.zoomed);resizeBoard();toast(state.zoomed?'Крупный вид: сетку можно прокручивать.':'Сетка снова целиком на экране.')};$('#theme-button').onclick=()=>document.body.classList.toggle('theme-dark');$('#back-button').onclick=()=>{const index=puzzles.findIndex(puzzle=>puzzle.id===state.puzzle.id);openPuzzle(puzzles[(index-1+puzzles.length)%puzzles.length])};$('#next-button').onclick=()=>{const index=puzzles.findIndex(puzzle=>puzzle.id===state.puzzle.id);openPuzzle(puzzles[(index+1)%puzzles.length])};$('#catalog-button').onclick=()=>{els.dialog.hidden=true;openDrawer(els.drawer)};els.input.oninput=event=>{const letter=event.target.value.toUpperCase().match(/[А-ЯЁ]/gu)?.at(-1);if(letter)enter(letter);event.target.value=''};document.addEventListener('keydown',event=>{if(!state)return;const pressed=event.key.toUpperCase();if(/^[А-ЯЁ]$/u.test(pressed)){event.preventDefault();enter(pressed)}if(event.key==='Backspace'){event.preventDefault();erase()}if(event.key==='ArrowLeft'){event.preventDefault();state.focus=Math.max(0,state.focus-1);render()}if(event.key==='ArrowRight'){event.preventDefault();state.focus=Math.min(activeWord().answer.length-1,state.focus+1);render()}});addEventListener('resize',resizeBoard);
window.render_game_to_text=()=>JSON.stringify({mode:els.dialog.hidden?'playing':'complete',version:'v7',puzzle:state.puzzle.number,category:state.puzzle.category,grid:{cols:state.puzzle.cols,rows:state.puzzle.rows,occupied:state.puzzle.cols*state.puzzle.rows},active:{clue:activeWord().clue,direction:arrowFor(activeWord()),length:activeWord().answer.length},filledCells:Object.keys(state.cells).length,totalCells:Object.keys(state.solution).length,complete:puzzleDone()});window.advanceTime=()=>{if(state)render()};
if(!puzzles.length)throw new Error('Нет сканвордов');openPuzzle(puzzles[0]);if('serviceWorker'in navigator&&location.protocol!=='file:')navigator.serviceWorker.register('./sw.js?v=7').catch(()=>{});
})();
