(function(){
'use strict';
const STORE='nadiia-scanwords-v5';
const puzzles=window.SCANWORD_PUZZLES||[];
const EXTRA=[...'АЕИОУЫЭЮЯБВГДЖЗЙКЛМНПРСТФХЦЧШЩ'];
const $=selector=>document.querySelector(selector);
const els={catalog:$('#catalog-screen'),game:$('#game-screen'),list:$('#puzzle-catalog'),progress:$('#catalog-progress'),filter:$('#category-filter'),grid:$('#scanword-grid'),board:$('.board-area'),title:$('#game-title'),category:$('#game-category'),tiles:$('#letter-tiles'),direction:$('#direction-badge'),clue:$('#active-length'),percent:$('#puzzle-percent'),feedback:$('#feedback'),dialog:$('#complete-dialog'),drawer:$('#drawer'),input:$('#native-input')};
let saved=readSaved(),state=null,category='Все';
function readSaved(){try{return JSON.parse(localStorage.getItem(STORE)||'{}')}catch{return {}}}
function persist(){try{localStorage.setItem(STORE,JSON.stringify(saved))}catch{}}
function key(row,col){return `${row}:${col}`}
function delta(word){return word.direction==='down'?[1,0]:word.direction==='left'?[0,-1]:[0,1]}
function wordCells(word){const [dr,dc]=delta(word);return [...word.answer].map((letter,index)=>({key:key(word.row+dr*index,word.col+dc*index),letter,index}))}
function solution(puzzle){const map={};puzzle.words.forEach(word=>wordCells(word).forEach(cell=>{map[cell.key]||={letter:cell.letter,wordIds:[]};map[cell.key].wordIds.push(word.id)}));return map}
function arrowFor(word){return word.arrow||(word.direction==='down'?'↓':word.direction==='left'?'←':'→')}
function portraitBoard(){return innerWidth<=600&&innerHeight>innerWidth}
function viewSize(){return state?.rotated?{rows:state.puzzle.cols,cols:state.puzzle.rows}:{rows:state.puzzle.rows,cols:state.puzzle.cols}}
function viewArrow(word){if(!state?.rotated)return arrowFor(word);return word.direction==='down'?'←':word.direction==='left'?'↑':'↓'}
function viewPosition(row,col){return state?.rotated?{row:col,col:state.puzzle.rows-1-row}:{row,col}}
function wordDone(word){return wordCells(word).every(cell=>state.cells[cell.key]===cell.letter)}
function puzzleDone(){return state&&Object.entries(state.solution).every(([cellKey,value])=>state.cells[cellKey]===value.letter)}
function saveGame(){if(!state)return;saved[state.puzzle.id]={cells:state.cells,completed:puzzleDone(),updatedAt:Date.now()};persist()}
function puzzlePercent(puzzle){const prior=saved[puzzle.id];if(!prior)return 0;const sol=solution(puzzle),done=Object.entries(sol).filter(([cellKey,value])=>prior.cells?.[cellKey]===value.letter).length;return Math.round(done/Object.keys(sol).length*100)}
function miniGrid(puzzle){const sol=solution(puzzle),clues=new Set(puzzle.words.map(word=>key(word.clueCell.row,word.clueCell.col)));let out='<span class="mini-grid" aria-hidden="true">';for(let row=0;row<puzzle.rows;row+=1)for(let col=0;col<puzzle.cols;col+=1){const cellKey=key(row,col);out+=`<i class="mini-cell ${sol[cellKey]?'':clues.has(cellKey)?'gray':'black'}"></i>`}return out+'</span>'}
function renderCatalog(){const shown=category==='Все'?puzzles:puzzles.filter(puzzle=>puzzle.category===category);const complete=puzzles.filter(puzzle=>saved[puzzle.id]?.completed).length;els.progress.textContent=`${complete} из ${puzzles.length}`;els.list.replaceChildren(...shown.map(puzzle=>{const pc=puzzlePercent(puzzle),button=document.createElement('button');button.className=`puzzle-card${pc===100?' is-complete':''}`;button.innerHTML=`${miniGrid(puzzle)}<span class="puzzle-label"><span>№${puzzle.number}</span><small>${pc?pc+'%':puzzle.words.length+' слов'}</small></span>`;button.onclick=()=>openPuzzle(puzzle);return button}));const inProgress=puzzles.filter(puzzle=>{const value=puzzlePercent(puzzle);return value>0&&value<100}).length,letters=Object.values(saved).reduce((sum,item)=>sum+Object.keys(item.cells||{}).length,0);$('#stat-completed').textContent=complete;$('#stat-progress').textContent=inProgress;$('#stat-letters').textContent=letters}
function resizeBoard(){if(!state||els.game.hidden)return;const rotated=portraitBoard();if(rotated!==state.rotated){state.rotated=rotated;render();return}const view=viewSize(),width=els.board.clientWidth,height=els.board.clientHeight,cell=Math.max(1,Math.min(width/view.cols,height/view.rows));els.grid.style.width=`${cell*view.cols}px`;els.grid.style.height=`${cell*view.rows}px`;els.grid.style.gridTemplateColumns=`repeat(${view.cols},1fr)`;els.grid.style.gridTemplateRows=`repeat(${view.rows},1fr)`;els.grid.style.setProperty('--cell',`${cell}px`);document.documentElement.style.setProperty('--board-cols',view.cols);document.documentElement.style.setProperty('--board-rows',view.rows)}
function openPuzzle(puzzle){const prior=saved[puzzle.id]||{};state={puzzle,solution:solution(puzzle),cells:{...(prior.cells||{})},activeWordId:puzzle.words[0].id,focus:0,solved:new Set(puzzle.words.filter(word=>wordCells(word).every(cell=>prior.cells?.[cell.key]===cell.letter)).map(word=>word.id)),tileOrder:{},extras:false,rotated:portraitBoard()};els.catalog.hidden=true;els.game.hidden=false;els.dialog.hidden=true;els.title.textContent=`№${puzzle.number}`;els.category.textContent=puzzle.category;selectWord(puzzle.words[0].id,true);requestAnimationFrame(resizeBoard)}
function closePuzzle(){saveGame();state=null;els.game.hidden=true;els.catalog.hidden=false;els.dialog.hidden=true;renderCatalog();scrollTo(0,0)}
function activeWord(){return state.puzzle.words.find(word=>word.id===state.activeWordId)}
function renderBoard(){const clues=new Map(state.puzzle.words.map(word=>[key(word.clueCell.row,word.clueCell.col),word])),active=activeWord(),activeCells=wordCells(active),activeKeys=new Set(activeCells.map(cell=>cell.key)),focusKey=activeCells[state.focus]?.key,fragment=document.createDocumentFragment(),positions=[];for(let row=0;row<state.puzzle.rows;row+=1)for(let col=0;col<state.puzzle.cols;col+=1)positions.push({originalRow:row,originalCol:col,...viewPosition(row,col)});positions.sort((a,b)=>a.row===b.row?a.col-b.col:a.row-b.row);for(const position of positions){const cellKey=key(position.originalRow,position.originalCol),word=clues.get(cellKey),sol=state.solution[cellKey],element=document.createElement(word||sol?'button':'div');element.className='grid-cell';if(word){element.classList.add('clue');element.dataset.wordId=word.id;if(word.id===state.activeWordId)element.classList.add('is-active');element.innerHTML=`<span class="clue-text">${word.clue}</span><b class="clue-arrow">${viewArrow(word)}</b>`;element.setAttribute('aria-label',`${word.clue}, ${viewArrow(word)}, ${word.answer.length} букв`);element.onclick=()=>selectWord(word.id)}else if(sol){element.classList.add('answer');element.textContent=state.cells[cellKey]||'';if(activeKeys.has(cellKey))element.classList.add('is-active');if(focusKey===cellKey)element.classList.add('is-focus');if(sol.wordIds.every(id=>state.solved.has(id)))element.classList.add('is-solved');element.onclick=()=>selectCell(cellKey)}else element.classList.add('blank');fragment.append(element)}els.grid.replaceChildren(fragment)}
function selectWord(id,initial=false){state.activeWordId=id;const cells=wordCells(activeWord()),firstEmpty=cells.findIndex(cell=>!state.cells[cell.key]);state.focus=firstEmpty<0?0:firstEmpty;state.extras=false;render();if(!initial)els.grid.querySelector('.is-focus')?.focus({preventScroll:true})}
function selectCell(cellKey){const ids=state.solution[cellKey].wordIds;state.activeWordId=ids.length>1&&ids.includes(state.activeWordId)?ids[(ids.indexOf(state.activeWordId)+1)%ids.length]:ids[0];state.focus=wordCells(activeWord()).findIndex(cell=>cell.key===cellKey);state.extras=false;render()}
function random(seed){let hash=2166136261;for(const char of seed)hash=Math.imul(hash^char.charCodeAt(0),16777619);return()=>((hash=Math.imul(hash^(hash>>>15),2246822507))>>>0)/4294967296}
function tileSet(word){if(state.tileOrder[word.id])return state.tileOrder[word.id];const rand=random(state.puzzle.id+word.id),all=[...word.answer].map((letter,index)=>({letter,extra:false,id:'a'+index}));while(all.length<20)all.push({letter:EXTRA[Math.floor(rand()*EXTRA.length)],extra:true,id:'e'+all.length});for(let index=all.length-1;index>0;index-=1){const swap=Math.floor(rand()*(index+1));[all[index],all[swap]]=[all[swap],all[index]]}return state.tileOrder[word.id]=all}
function renderTiles(){const word=activeWord(),tiles=tileSet(word).filter(tile=>!state.extras||!tile.extra);els.tiles.replaceChildren(...tiles.map(tile=>{const button=document.createElement('button');button.className=`letter-tile${tile.extra?' is-extra':''}`;button.textContent=tile.letter;button.onclick=()=>enter(tile.letter);return button}));$('#hint-extras').disabled=state.extras}
function nextEmpty(cells,start){for(let count=0;count<cells.length;count+=1){const index=(start+count)%cells.length;if(!state.cells[cells[index].key])return index}return Math.min(start,cells.length-1)}
function enter(letter){if(!/^[А-ЯЁ]$/u.test(letter))return;const cells=wordCells(activeWord()),index=state.focus;state.cells[cells[index].key]=letter;state.focus=nextEmpty(cells,index+1);afterEdit()}
function erase(){const cells=wordCells(activeWord());let index=state.focus;if(!state.cells[cells[index].key]&&index>0)index-=1;delete state.cells[cells[index].key];state.focus=index;state.solved.delete(state.activeWordId);els.feedback.textContent='';saveGame();render()}
function reveal(){const cells=wordCells(activeWord()),index=cells.findIndex(cell=>state.cells[cell.key]!==cell.letter);if(index<0)return;state.cells[cells[index].key]=cells[index].letter;state.focus=nextEmpty(cells,index+1);afterEdit()}
function revealWord(){wordCells(activeWord()).forEach(cell=>{state.cells[cell.key]=cell.letter});afterEdit()}
function afterEdit(){const newly=[];state.puzzle.words.forEach(word=>{if(wordDone(word)&&!state.solved.has(word.id)){state.solved.add(word.id);newly.push(word)}});saveGame();render();if(newly.length){els.feedback.textContent='Верно! Отличное слово ✦';sparkleWord()}else els.feedback.textContent='';if(puzzleDone())setTimeout(finish,220)}
function sparkleWord(){const box=els.grid.getBoundingClientRect();for(let index=0;index<12;index+=1){const spark=document.createElement('i');spark.className='spark';spark.textContent='✦';spark.style.left=`${box.left+box.width/2}px`;spark.style.top=`${box.top+box.height/2}px`;spark.style.setProperty('--x',`${(Math.random()-.5)*180}px`);spark.style.setProperty('--y',`${(Math.random()-.5)*140}px`);document.body.append(spark);setTimeout(()=>spark.remove(),800)}}
function launchConfetti(){const canvas=$('#confetti'),context=canvas.getContext('2d');canvas.width=innerWidth;canvas.height=innerHeight;const bits=Array.from({length:150},()=>({x:Math.random()*canvas.width,y:-Math.random()*canvas.height*.5,v:2+Math.random()*5,s:3+Math.random()*5,h:Math.random()*360}));let frame=0;(function draw(){context.clearRect(0,0,canvas.width,canvas.height);bits.forEach(bit=>{bit.y+=bit.v;bit.x+=Math.sin((bit.y+bit.h)/28);context.fillStyle=`hsl(${bit.h} 70% 48%)`;context.fillRect(bit.x,bit.y,bit.s,bit.s*1.7)});if(frame++<150)requestAnimationFrame(draw);else context.clearRect(0,0,canvas.width,canvas.height)})()}
function finish(){if(!els.dialog.hidden)return;saveGame();launchConfetti();els.dialog.hidden=false}
function render(){renderBoard();renderTiles();const word=activeWord();els.direction.textContent=viewArrow(word);els.clue.textContent=`${word.clue} · ${word.answer.length} букв`;const total=Object.keys(state.solution).length,done=Object.entries(state.solution).filter(([cellKey,value])=>state.cells[cellKey]===value.letter).length;els.percent.textContent=`${Math.round(done/total*100)}%`;resizeBoard()}
function initCategories(){const categories=['Все',...new Set(puzzles.map(puzzle=>puzzle.category))];els.filter.replaceChildren(...categories.map(value=>{const option=document.createElement('option');option.value=option.textContent=value;return option}));els.filter.onchange=()=>{category=els.filter.value;renderCatalog()}}
function showTab(name){document.querySelectorAll('.tab').forEach(button=>button.classList.toggle('is-active',button.dataset.tab===name));$('#list-panel').hidden=name!=='list';$('#stats-panel').hidden=name!=='stats';renderCatalog()}
document.querySelectorAll('.tab').forEach(button=>button.onclick=()=>showTab(button.dataset.tab));$('#back-button').onclick=closePuzzle;$('#catalog-button').onclick=closePuzzle;$('#next-button').onclick=()=>{const index=puzzles.findIndex(puzzle=>puzzle.id===state.puzzle.id);openPuzzle(puzzles[(index+1)%puzzles.length])};$('#delete-button').onclick=erase;$('#hint-letter').onclick=reveal;$('#hint-word').onclick=revealWord;$('#hint-extras').onclick=()=>{state.extras=true;renderTiles()};$('#keyboard-toggle').onclick=()=>{els.input.value='';els.input.focus()};els.input.oninput=event=>{const letter=event.target.value.toUpperCase().match(/[А-ЯЁ]/gu)?.at(-1);if(letter)enter(letter);event.target.value=''};document.addEventListener('keydown',event=>{if(!state||els.game.hidden)return;const pressed=event.key.toUpperCase();if(/^[А-ЯЁ]$/u.test(pressed)){event.preventDefault();enter(pressed)}if(event.key==='Backspace'){event.preventDefault();erase()}});$('#menu-button').onclick=()=>{els.drawer.classList.add('open');els.drawer.setAttribute('aria-hidden','false')};$('#close-menu').onclick=()=>{els.drawer.classList.remove('open');els.drawer.setAttribute('aria-hidden','true')};$('#drawer-list').onclick=()=>{els.drawer.classList.remove('open');showTab('list')};$('#reset-progress').onclick=()=>{if(confirm('Сбросить весь прогресс?')){saved={};persist();renderCatalog()}};els.drawer.onclick=event=>{if(event.target===els.drawer)$('#close-menu').click()};addEventListener('resize',resizeBoard);
window.render_game_to_text=()=>{const view=state?viewSize():null;return JSON.stringify(!state?{mode:'catalog',puzzles:puzzles.length,category}:{mode:els.dialog.hidden?'playing':'complete',puzzle:state.puzzle.number,category:state.puzzle.category,grid:{cols:view.cols,rows:view.rows,occupied:state.puzzle.cols*state.puzzle.rows},active:{clue:activeWord().clue,direction:viewArrow(activeWord()),length:activeWord().answer.length},filledCells:Object.keys(state.cells).length,totalCells:Object.keys(state.solution).length,complete:puzzleDone()})};window.advanceTime=()=>{if(state)render();else renderCatalog()};
initCategories();renderCatalog();if('serviceWorker'in navigator&&location.protocol!=='file:')navigator.serviceWorker.register('./sw.js?v=5').catch(()=>{});
})();
