(function(){
'use strict';
const STORE='nadiia-scanwords-v4';
const puzzles=window.SCANWORD_PUZZLES||[];
const EXTRA=[...'АЕИОУЫЭЮЯБВГДЖЗЙКЛМНПРСТФХЦЧШЩ'];
const $=s=>document.querySelector(s);
const els={catalog:$('#catalog-screen'),game:$('#game-screen'),list:$('#puzzle-catalog'),progress:$('#catalog-progress'),filter:$('#category-filter'),grid:$('#scanword-grid'),title:$('#game-title'),category:$('#game-category'),tiles:$('#letter-tiles'),direction:$('#direction-badge'),clue:$('#active-length'),percent:$('#puzzle-percent'),feedback:$('#feedback'),dialog:$('#complete-dialog'),drawer:$('#drawer'),input:$('#native-input')};
let saved=readSaved(),state=null,category='Все';
function readSaved(){try{return JSON.parse(localStorage.getItem(STORE)||'{}')}catch{return {}}}
function persist(){try{localStorage.setItem(STORE,JSON.stringify(saved))}catch{}}
function key(r,c){return `${r}:${c}`}
function wordCells(w){return [...w.answer].map((letter,i)=>({key:key(w.row+(w.direction==='down'?i:0),w.col+(w.direction==='across'?i:0)),letter,index:i}))}
function solution(p){const map={};p.words.forEach(w=>wordCells(w).forEach(c=>{map[c.key]||={letter:c.letter,wordIds:[]};map[c.key].wordIds.push(w.id)}));return map}
function arrowFor(w){if(w.direction==='down')return '↓';return Number(w.id.replace(/\D/g,''))%3===0?'←':'→'}
function wordDone(w){return wordCells(w).every(c=>state.cells[c.key]===c.letter)}
function puzzleDone(){return state&&Object.entries(state.solution).every(([k,v])=>state.cells[k]===v.letter)}
function saveGame(){if(!state)return;saved[state.puzzle.id]={cells:state.cells,completed:puzzleDone(),updatedAt:Date.now()};persist()}
function puzzlePercent(p){const s=saved[p.id];if(!s)return 0;const sol=solution(p),done=Object.entries(sol).filter(([k,v])=>s.cells?.[k]===v.letter).length;return Math.round(done/Object.keys(sol).length*100)}
function miniGrid(p){const sol=solution(p),clues=new Set(p.words.map(w=>key(w.clueCell.row,w.clueCell.col)));let out='<span class="mini-grid" aria-hidden="true">';for(let r=0;r<8;r++)for(let c=0;c<8;c++){const rr=Math.floor(r*p.rows/8),cc=Math.floor(c*p.cols/8),k=key(rr,cc);out+=`<i class="mini-cell ${sol[k]?'':clues.has(k)?'gray':'black'}"></i>`}return out+'</span>'}
function renderCatalog(){const shown=category==='Все'?puzzles:puzzles.filter(p=>p.category===category);const complete=puzzles.filter(p=>saved[p.id]?.completed).length;els.progress.textContent=`${complete} из ${puzzles.length}`;els.list.replaceChildren(...shown.map(p=>{const pc=puzzlePercent(p),b=document.createElement('button');b.className=`puzzle-card${pc===100?' is-complete':''}`;b.innerHTML=`${miniGrid(p)}<span class="puzzle-label"><span>№${p.number}</span><small>${pc?pc+'%':p.words.length+' слов'}</small></span>`;b.onclick=()=>openPuzzle(p);return b}));const inProgress=puzzles.filter(p=>{const x=puzzlePercent(p);return x>0&&x<100}).length,letters=Object.values(saved).reduce((n,x)=>n+Object.keys(x.cells||{}).length,0);$('#stat-completed').textContent=complete;$('#stat-progress').textContent=inProgress;$('#stat-letters').textContent=letters}
function openPuzzle(p){const old=saved[p.id]||{};state={puzzle:p,solution:solution(p),cells:{...(old.cells||{})},activeWordId:p.words[0].id,focus:0,solved:new Set(p.words.filter(w=>wordCells(w).every(c=>old.cells?.[c.key]===c.letter)).map(w=>w.id)),tileOrder:{},extras:false};els.catalog.hidden=true;els.game.hidden=false;els.dialog.hidden=true;els.title.textContent=`№${p.number}`;els.category.textContent=p.category;selectWord(p.words[0].id,true)}
function closePuzzle(){saveGame();state=null;els.game.hidden=true;els.catalog.hidden=false;els.dialog.hidden=true;renderCatalog();scrollTo(0,0)}
function activeWord(){return state.puzzle.words.find(w=>w.id===state.activeWordId)}
function renderBoard(){const clues=new Map(state.puzzle.words.map(w=>[key(w.clueCell.row,w.clueCell.col),w])),active=activeWord(),activeKeys=new Set(wordCells(active).map(c=>c.key)),frag=document.createDocumentFragment();for(let r=0;r<state.puzzle.rows;r++)for(let c=0;c<state.puzzle.cols;c++){const k=key(r,c),w=clues.get(k),sol=state.solution[k],el=document.createElement(w||sol?'button':'div');el.className='grid-cell';if(w){el.classList.add('clue');if(w.id===state.activeWordId)el.classList.add('is-active');el.innerHTML=`<span class="clue-text">${w.clue}</span><b class="clue-arrow">${arrowFor(w)}</b>`;el.onclick=()=>selectWord(w.id)}else if(sol){el.classList.add('answer');el.textContent=state.cells[k]||'';if(activeKeys.has(k))el.classList.add('is-active');if(wordCells(active)[state.focus]?.key===k)el.classList.add('is-focus');if(sol.wordIds.every(id=>state.solved.has(id)))el.classList.add('is-solved');el.onclick=()=>selectCell(k)}else el.classList.add('blank');frag.append(el)}els.grid.replaceChildren(frag)}
function selectWord(id,initial=false){state.activeWordId=id;const cells=wordCells(activeWord());state.focus=Math.max(0,cells.findIndex(c=>!state.cells[c.key]));state.extras=false;render();if(!initial)els.grid.querySelector('.is-focus')?.focus({preventScroll:true})}
function selectCell(k){const ids=state.solution[k].wordIds;state.activeWordId=ids.length>1&&ids.includes(state.activeWordId)?ids[(ids.indexOf(state.activeWordId)+1)%ids.length]:ids[0];state.focus=wordCells(activeWord()).findIndex(c=>c.key===k);state.extras=false;render()}
function random(seed){let h=2166136261;for(const ch of seed)h=Math.imul(h^ch.charCodeAt(0),16777619);return()=>((h=Math.imul(h^(h>>>15),2246822507))>>>0)/4294967296}
function tileSet(w){if(state.tileOrder[w.id])return state.tileOrder[w.id];const rand=random(state.puzzle.id+w.id),all=[...w.answer].map((letter,i)=>({letter,extra:false,id:'a'+i}));while(all.length<20)all.push({letter:EXTRA[Math.floor(rand()*EXTRA.length)],extra:true,id:'e'+all.length});for(let i=all.length-1;i;i--){const j=Math.floor(rand()*(i+1));[all[i],all[j]]=[all[j],all[i]]}return state.tileOrder[w.id]=all}
function renderTiles(){const w=activeWord(),tiles=tileSet(w).filter(t=>!state.extras||!t.extra);els.tiles.replaceChildren(...tiles.map(t=>{const b=document.createElement('button');b.className='letter-tile';b.textContent=t.letter;b.onclick=()=>enter(t.letter);return b}));$('#hint-extras').disabled=state.extras}
function nextEmpty(cells,start){for(let n=0;n<cells.length;n++){const i=(start+n)%cells.length;if(!state.cells[cells[i].key])return i}return Math.min(start,cells.length-1)}
function enter(letter){if(!/^[А-ЯЁ]$/u.test(letter))return;const cells=wordCells(activeWord()),i=state.focus;state.cells[cells[i].key]=letter;state.focus=nextEmpty(cells,i+1);afterEdit()}
function erase(){const cells=wordCells(activeWord());let i=state.focus;if(!state.cells[cells[i].key]&&i>0)i--;delete state.cells[cells[i].key];state.focus=i;state.solved.delete(state.activeWordId);els.feedback.textContent='';saveGame();render()}
function reveal(){const cells=wordCells(activeWord());let i=cells.findIndex(c=>state.cells[c.key]!==c.letter);if(i<0)return;state.cells[cells[i].key]=cells[i].letter;state.focus=nextEmpty(cells,i+1);afterEdit()}
function afterEdit(){const newly=[];state.puzzle.words.forEach(w=>{if(wordDone(w)&&!state.solved.has(w.id)){state.solved.add(w.id);newly.push(w)}});saveGame();render();if(newly.length){els.feedback.textContent='Верно! Отличное слово ✦';sparkleWord()}else els.feedback.textContent='';if(puzzleDone())setTimeout(finish,220)}
function sparkleWord(){const box=els.grid.getBoundingClientRect();for(let i=0;i<12;i++){const s=document.createElement('i');s.className='spark';s.textContent='✦';s.style.left=`${box.left+box.width/2}px`;s.style.top=`${box.top+box.height/2}px`;s.style.setProperty('--x',`${(Math.random()-.5)*180}px`);s.style.setProperty('--y',`${(Math.random()-.5)*140}px`);document.body.append(s);setTimeout(()=>s.remove(),800)}}
function launchConfetti(){const c=$('#confetti'),x=c.getContext('2d');c.width=innerWidth;c.height=innerHeight;const bits=Array.from({length:150},()=>({x:Math.random()*c.width,y:-Math.random()*c.height*.5,v:2+Math.random()*5,s:3+Math.random()*5,h:Math.random()*360}));let f=0;(function draw(){x.clearRect(0,0,c.width,c.height);bits.forEach(b=>{b.y+=b.v;b.x+=Math.sin((b.y+b.h)/28);x.fillStyle=`hsl(${b.h} 70% 48%)`;x.fillRect(b.x,b.y,b.s,b.s*1.7)});if(f++<150)requestAnimationFrame(draw);else x.clearRect(0,0,c.width,c.height)})()}
function finish(){if(!els.dialog.hidden)return;saveGame();launchConfetti();els.dialog.hidden=false}
function render(){renderBoard();renderTiles();const w=activeWord();els.direction.textContent=arrowFor(w);els.clue.textContent=`${w.clue} · ${w.answer.length} букв`;const total=Object.keys(state.solution).length,done=Object.entries(state.solution).filter(([k,v])=>state.cells[k]===v.letter).length;els.percent.textContent=`${Math.round(done/total*100)}%`}
function initCategories(){const cats=['Все',...new Set(puzzles.map(p=>p.category))];els.filter.replaceChildren(...cats.map(c=>{const o=document.createElement('option');o.value=o.textContent=c;return o}));els.filter.onchange=()=>{category=els.filter.value;renderCatalog()}}
function showTab(name){document.querySelectorAll('.tab').forEach(b=>b.classList.toggle('is-active',b.dataset.tab===name));$('#list-panel').hidden=name!=='list';$('#stats-panel').hidden=name!=='stats';renderCatalog()}
document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>showTab(b.dataset.tab));$('#back-button').onclick=closePuzzle;$('#catalog-button').onclick=closePuzzle;$('#next-button').onclick=()=>{const i=puzzles.findIndex(p=>p.id===state.puzzle.id);openPuzzle(puzzles[(i+1)%puzzles.length])};$('#delete-button').onclick=erase;$('#hint-letter').onclick=reveal;$('#hint-extras').onclick=()=>{state.extras=true;renderTiles()};$('#keyboard-toggle').onclick=()=>{els.input.value='';els.input.focus()};els.input.oninput=e=>{const ch=e.target.value.toUpperCase().match(/[А-ЯЁ]/gu)?.at(-1);if(ch)enter(ch);e.target.value=''};document.addEventListener('keydown',e=>{if(!state||els.game.hidden)return;const k=e.key.toUpperCase();if(/^[А-ЯЁ]$/u.test(k)){e.preventDefault();enter(k)}if(e.key==='Backspace'){e.preventDefault();erase()}});$('#menu-button').onclick=()=>{els.drawer.classList.add('open');els.drawer.setAttribute('aria-hidden','false')};$('#close-menu').onclick=()=>{els.drawer.classList.remove('open');els.drawer.setAttribute('aria-hidden','true')};$('#drawer-list').onclick=()=>{els.drawer.classList.remove('open');showTab('list')};$('#reset-progress').onclick=()=>{if(confirm('Сбросить весь прогресс?')){saved={};persist();renderCatalog()}};els.drawer.onclick=e=>{if(e.target===els.drawer)$('#close-menu').click()};
window.render_game_to_text=()=>JSON.stringify(!state?{mode:'catalog',puzzles:puzzles.length,category}:{mode:els.dialog.hidden?'playing':'complete',puzzle:state.puzzle.number,category:state.puzzle.category,active:{clue:activeWord().clue,direction:arrowFor(activeWord()),length:activeWord().answer.length},filled:Object.keys(state.cells).length,total:Object.keys(state.solution).length});window.advanceTime=()=>{if(state)render();else renderCatalog()};
initCategories();renderCatalog();if('serviceWorker'in navigator&&location.protocol!=='file:')navigator.serviceWorker.register('./sw.js').catch(()=>{});
})();
